import { z } from "zod";
import { DaypartSchema, EvidenceGradeSchema, SectorSchema } from "@/contracts/domain";

const ScoreSchema = z.object({
  A: z.number().min(0).max(100),
  C: z.number().min(0).max(100),
  P: z.number().min(0).max(100),
  E: z.number().min(0).max(100),
});

const EvidenceComponentsSchema = z.object({
  source: z.number().min(0).max(100),
  validation: z.number().min(0).max(100),
  temporal: z.number().min(0).max(100),
  granularityCoverage: z.number().min(0).max(100),
  completeness: z.number().min(0).max(100),
  minimumCritical: z.number().min(0).max(100),
  caps: z.array(z.number().min(0).max(100)).min(1),
  hasZeroCritical: z.boolean(),
});

export const FrozenBundleSchema = z.object({
  manifest: z.object({
    id: z.literal("lagos-demo-v1"),
    geographyId: z.literal("lagos-demo-v1"),
    schemaVersion: z.literal("1.0.0"),
    createdAt: z.literal("2026-08-03T12:00:00.000Z"),
    maximumEvidenceGrade: EvidenceGradeSchema,
    synthetic: z.boolean(),
    seed: z.literal(260803),
    modelVersion: z.literal("conditional-poisson-demo-v1"),
    featureSnapshotId: z.literal("lagos-synthetic-features-v1"),
    featureSchemaCompatibilityId: z.string().min(1),
    targetUniverseVersion: z.literal("lagos-target-universe-v1"),
    panelVersion: z.literal("weighted-panel-v1"),
    replicateSetId: z.literal("scenario-low-base-high-v1"),
    targetCellPartitionId: z.literal("mutually-exclusive-sector-cells-v1"),
    targetCellAssignmentRule: z.literal("ordered-first-match-with-residual-v1"),
    evidenceProfileVersion: z.literal("synthetic-evidence-profiles-v1"),
    scheduleModelVersion: z.literal("inclusive-daily-daypart-v1"),
    influenceLinkageAssumptionId: z.literal("conditional-independence-within-target-cell-v1"),
    influenceSensitivityId: z.literal("coherent-exposure-scaling-low-base-high-v1"),
    dataRevision: z.literal("lagos-demo-data-r1"),
  }),
  zones: z.array(z.object({
    id: z.string().min(1),
    label: z.string().min(1),
    center: z.tuple([z.number(), z.number()]),
  })).min(5),
  sites: z.array(z.object({
    id: z.string().min(1),
    zoneId: z.string().min(1),
    label: z.string().min(1),
    supplierId: z.string().min(1),
    coordinate: z.tuple([z.number(), z.number()]),
    format: z.enum(["static", "dooh"]),
    rateNgn: z.number().positive(),
    baseMovement: z.record(DaypartSchema, z.number().positive()),
    visibility: z.number().min(0).max(1),
    deliverySchedule: z.object({
      availabilityStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
      availabilityEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
      uptime: z.number().min(0).max(1),
      shareOfTime: z.number().min(0).max(1),
      availabilityRevision: z.string().min(1),
      uptimeRevision: z.string().min(1),
      shareOfTimeRevision: z.string().min(1),
    }),
    targetShareBySector: z.record(SectorSchema, z.record(z.string(), z.number().min(0).max(1))),
    planningScoresBySector: z.record(SectorSchema, ScoreSchema),
    available: z.boolean(),
  })).min(10),
  activityCohort: z.array(z.object({
    id: z.string().min(1),
    zoneId: z.string().min(1),
    value: z.number().positive(),
  })).min(30),
  targets: z.array(z.object({
    sector: SectorSchema,
    cellId: z.string().min(1),
    universe: z.number().positive(),
    universeSourceId: z.string().min(1),
    membership: z.literal("mutually_exclusive"),
    defaultQi: z.number().min(0).max(1),
    qiSourceId: z.string().min(1),
    defaultServiceability: z.number().min(0).max(1),
    serviceabilitySourceId: z.string().min(1),
  })).min(9),
  targetAllocationSourceIds: z.record(SectorSchema, z.string().min(1)),
  panel: z.array(z.object({
    id: z.string().min(1),
    sector: SectorSchema,
    cellId: z.string().min(1),
    weight: z.number().positive(),
    qi: z.number().min(0).max(1),
    serviceability: z.number().min(0).max(1),
    zoneAffinity: z.record(z.string(), z.number().positive()),
    timeAffinity: z.record(DaypartSchema, z.number().positive()),
  })).min(200),
  scenarios: z.array(z.object({
    id: z.enum(["low", "base", "high"]),
    movementMultiplier: z.number().positive(),
    visibilityMultiplier: z.number().positive(),
    targetShareMultiplier: z.number().positive(),
    propensityConcentration: z.number().positive(),
  })).length(3),
  scalingEnvelope: z.object({
    minimumC: z.number().positive(),
    maximumC: z.number().positive(),
    maximumMemberLambda: z.number().positive(),
    maximumAverageFrequency: z.number().positive(),
  }),
  featureRegistry: z.array(z.object({
    id: z.string().min(1),
    role: z.enum(["measurement", "score"]),
    pillar: z.enum(["A", "D", "C", "P", "E"]).nullable(),
  })),
  sourceManifest: z.array(z.object({
    id: z.string().min(1),
    kind: z.enum([
      "inventory",
      "target_universe",
      "target_allocation",
      "influence",
      "serviceability",
    ]),
    sector: SectorSchema.nullable(),
    geographyId: z.literal("lagos-demo-v1"),
    productScope: z.enum(["all", "fmcg", "real_estate", "bank_fintech"]),
    periodStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    periodEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    provenance: z.literal("synthetic"),
    rendererEligibility: z.literal("maplibre"),
    modelUse: z.literal("demo_only"),
  })),
  evidenceProfiles: z.object({
    recommendation: EvidenceComponentsSchema,
    activityPotential: EvidenceComponentsSchema,
    movement: EvidenceComponentsSchema,
    generalOts: EvidenceComponentsSchema,
    targetOts: EvidenceComponentsSchema,
    reach: EvidenceComponentsSchema,
    influence: EvidenceComponentsSchema,
    serviceability: EvidenceComponentsSchema,
  }),
  calibrationReport: z.object({
    heldOutLocations: z.number().int().nonnegative(),
    directionalBlocks: z.number().int().nonnegative(),
    mdape: z.number().nonnegative(),
    wape: z.number().nonnegative(),
    intervalCoverage: z.number().min(0).max(1),
    absoluteSignedWape: z.number().nonnegative(),
    worstEligibleStratumAbsoluteSignedWape: z.number().nonnegative(),
    independentDateReplication: z.boolean(),
    claimInputsComplete: z.boolean(),
    insideApplicabilityEnvelope: z.boolean(),
    downstreamProtocolRegistered: z.boolean(),
    downstreamValidation: z.object({
      ots: z.boolean(),
      targetOts: z.boolean(),
      uniqueReach: z.boolean(),
      influence: z.boolean(),
    }),
  }).optional(),
});

export type FrozenBundle = z.infer<typeof FrozenBundleSchema>;
